version: '3.9'

services:
  mysql-db:
    image: mysql:8.3.0
    container_name: mysql-parser-db-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: parser-db
      MYSQL_USER: userName
      MYSQL_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
